#!/bin/bash

# ------------------- install vars
# tested and working with 5.6.4.2
# https://github.com/aircrack-ng/rtl8812au

VERSION=$1

# ------------------- setup wifi adapter realtek rtl8812au

cd /tmp 
git clone -b v$VERSION https://github.com/aircrack-ng/rtl8812au.git
cd rtl8812au
sed -i 's/CONFIG_PLATFORM_ARM64_RPI = n/CONFIG_PLATFORM_ARM64_RPI = y/g' Makefile
sudo make dkms_install

reboot

